
kind:        Service
apiVersion:  v1

metadata:
  name:      bbdd      # Este es el nombre que se da de alta en el DNS interno de kubernetes
                       # Asociado a una IP FIJA, que el propio cluster asigna

spec:
  #type:      ClusterIP   # Es el valor por defecto. Son los que sirven para comunicación interna entre pods
  ports:
    - port:        3307        # Puerto de la ip fija del servicio
      targetPort:  3306        # Puerto del contenedor al que se redirige el tráfico
  
  selector:
    app:         mariadb      # El servicio selecciona los pods (del mismo namespace) que tengan esta etiqueta
---


kind:        Service
apiVersion:  v1

metadata:
  name:      wordpress
                      
spec:
  type:      NodePort   # Este tipo de servicio es accesible desde fuera del cluster
  ports:
    - port:        8888        # Puerto de la ip fija del servicio
      targetPort:  80        # Puerto del contenedor al que se redirige el tráfico
      nodePort:    30001     # Puerto del nodo (host) por el que se accede al servicio desde fuera del cluster
      # No solemos hacerlo... ya que no sabemos si otro equipo ha desplegado una app en ese puerto.
  selector:
    app:         wordpress
